### ISSUE TITLE
gradle issue

### ISSUE THREAD

**Issue by ryanechternacht** [rundef/poker-equity-calculator#2]
When I tried to build it, I got this error

```
A problem was found with the configuration of task ':startScripts'.
> No value has been specified for property 'mainClassName'.
```

Adding this as the 3rd line of `build.grade` fixed it

`mainClassName = 'com.rundef.poker.Console'`

NB: I'm not a java dev at all -- so perhaps there is a better way to do this.

**Comment by rundef** [comment]
Thank you! I just made the change in the repo
